import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Star } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { createStrategy, getPieceCode, getPieceColor, type OptimizerInput, type Placement, type StrategyResult } from '@/services/optimizerEngine';

const fallback: OptimizerInput = { width: 150, length: 20, cost: 250, gap: .5, garment: 'Shirt', quantity: 50, pieces: [{ id: 1, name: 'Front', width: 70, height: 50, quantity: 1, rotation: true }, { id: 2, name: 'Back', width: 70, height: 50, quantity: 1, rotation: true }, { id: 3, name: 'Sleeve', width: 60, height: 30, quantity: 2, rotation: true }, { id: 4, name: 'Collar', width: 40, height: 20, quantity: 1, rotation: false }] };
const garmentName = (name: string) => name === 'Shirt' ? "Men's Shirt" : name === 'Pants' ? "Men's Pants" : name === 'Shorts' ? "Men's Shorts" : name;
const OptimizationResults: React.FC = () => {
  const navigate = useNavigate(); const [zoom, setZoom] = useState<string | null>(null); const [zoomScale, setZoomScale] = useState(4.5);
  const input = useMemo<OptimizerInput>(() => { try { const saved = JSON.parse(localStorage.getItem('ecocut:optimizer') || ''); return saved?.pieces ? saved : fallback; } catch { return fallback; } }, []);
  const strategies = useMemo(() => ['standard', 'rotated', 'optimized'].map((key) => createStrategy(input, key as StrategyResult['key'])), [input]); const standard = strategies[0]; const winning = strategies.reduce((current, candidate) => candidate.garmentsPlaced > current.garmentsPlaced || (candidate.garmentsPlaced === current.garmentsPlaced && (candidate.fabricUsed < current.fabricUsed || (candidate.fabricUsed === current.fabricUsed && (candidate.wastePercent < current.wastePercent || (candidate.wastePercent === current.wastePercent && candidate.utilization > current.utilization))))) ? candidate : current); const best = winning;
  const unused = Math.max(0, input.length - best.fabricUsed); const savings = standard.fabricUsed - best.fabricUsed;
  return <div className="min-h-screen bg-[#f7f9fb] p-4 text-[#0b1d46] lg:p-5"><div className="mx-auto max-w-[1560px]">
    <div className="grid gap-3 xl:grid-cols-[1.1fr_1fr_1fr_1.15fr]"><InputSummary input={input} /><GarmentSummary input={input} /><Legend input={input} /><ProductionSummary input={input} result={best} unused={unused} /></div>
    <h1 className="mt-3 text-2xl font-bold">Cutting Strategy Comparison</h1><p className="text-lg text-[#536b93]">Different ways to arrange {input.quantity} {input.garment.toLowerCase()}s on a {input.width} cm × {input.length} m fabric roll</p>
    <div className="mt-3 grid gap-5 xl:grid-cols-3">{strategies.map((result, index) => <StrategyCard key={result.key} input={input} result={result} index={index} isBest={result.key === winning.key} expanded={zoom === result.key} onZoom={() => { setZoom(zoom === result.key ? null : result.key); setZoomScale(4.5); }} />)}</div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#132a4c] p-4 text-white"><div className="flex items-center gap-3"><CheckCircle2 className="h-7 w-7 text-[#3de080]" /><span><b>Result:</b> Strategy {best.key === 'standard' ? 'A' : best.key === 'rotated' ? 'B' : 'C'} saves {savings.toFixed(1)} m of fabric (₹{Math.round(savings * input.cost).toLocaleString('en-IN')}) compared to Strategy A and reduces waste by {(standard.wastePercent - best.wastePercent).toFixed(1)} percentage points.</span></div><button onClick={() => navigate('/layouts')} className="inline-flex items-center gap-2 rounded-lg bg-white px-5 py-2.5 font-bold text-[#102548]">View Detailed Report <ArrowRight className="h-4 w-4" /></button></div>
    <button onClick={() => navigate('/project')} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[#315781]"><ArrowLeft className="h-4 w-4" /> Adjust optimizer inputs</button>
    {zoom && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-6"><div className="flex max-h-full w-full max-w-6xl flex-col rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">Complete Cutting Layout</h2><p className="text-sm text-[#536b93]">Scroll to pan the full marker; hover a piece to inspect its dimensions and garment number.</p></div><div className="flex items-center gap-2"><button onClick={() => setZoomScale((value) => Math.max(2, value - 1))} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold" aria-label="Zoom out">−</button><span className="text-xs font-bold text-slate-600">{Math.round(zoomScale / 4.5 * 100)}%</span><button onClick={() => setZoomScale((value) => Math.min(8, value + 1))} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold" aria-label="Zoom in">+</button><button onClick={() => setZoom(null)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold">Close</button></div></div><div className="min-h-0 overflow-auto rounded-xl border border-slate-200 bg-slate-100 p-5"><CuttingDiagram input={input} result={strategies.find((strategy) => strategy.key === zoom) || best} expanded scale={zoomScale} onZoom={() => undefined} /></div><PieceKey input={input} /></div></div>}
  </div></div>;
};
const InputSummary = ({ input }: { input: OptimizerInput }) => <section className="rounded-lg border border-[#d9e3ef] bg-white p-3"><h2 className="text-lg font-bold">Input Summary</h2><div className="mt-3 grid grid-cols-3 gap-y-8">{[['Fabric Width', `${input.width} cm`], ['Fabric Length', `${input.length} m`], ['Total Fabric Area', `${(input.width / 100 * input.length).toFixed(1)} m²`], ['Fabric Type', input.fabric || 'Cotton'], ['Grain Direction', input.grainDirection || 'Lengthwise'], ['Fabric Cost', `₹${input.cost} / m`], ['Cutting Gap', `${input.gap} cm`]].map(([label, value]) => <div key={label}><div className="text-sm text-[#49628b]">{label}</div><div className="mt-1 font-bold">{value}</div></div>)}</div></section>;
const GarmentSummary = ({ input }: { input: OptimizerInput }) => <section className="rounded-lg border border-[#d9e3ef] bg-white p-3"><h2 className="text-lg font-bold">Selected Garment</h2><div className="mt-2 flex gap-3"><GarmentPreview garment={input.garment} /><div><h3 className="font-bold">{garmentName(input.garment)}</h3><p className="mt-1 text-sm text-[#425b85]">Size: {input.size || 'M'}</p><p className="mt-1 text-sm text-[#425b85]">Quantity: <b>{input.quantity}</b></p><div className="mt-2 rounded-md bg-[#f0f5fb] p-2 text-xs"><b>Pattern Pieces per {input.garment}</b><div className="mt-1 grid grid-cols-2 gap-x-3 gap-y-1">{input.pieces.map((p) => <span key={p.id}>{p.name} · {p.quantity}</span>)}</div></div></div></div></section>;
const GarmentPreview = ({ garment }: { garment: string }) => {
  const offset = garment === 'Pants' || garment === 'Kids Pants' ? 'translateX(-50%)' : garment === 'Shorts' ? 'translateY(-50%)' : garment === 'Dress' ? 'translate(-50%, -50%)' : 'none';
  return <div className="h-40 w-32 shrink-0 overflow-hidden rounded-md border border-[#d7e3f0] bg-[#101a27]" title={`${garmentName(garment)} product preview`}><img src="/garments/garment-contact-sheet.png" alt={`${garmentName(garment)} product`} className="h-[200%] w-[200%] max-w-none object-cover" style={{ transform: offset }} /></div>;
};
const Legend = ({ input }: { input: OptimizerInput }) => <section className="rounded-lg border border-[#d9e3ef] bg-white p-3"><h2 className="text-base font-bold">Pattern Piece Colors</h2><div className="mt-2 grid gap-1.5">{input.pieces.map((p) => <div key={p.id} className="flex items-center gap-2 text-sm"><i className="h-5 w-5 rounded border border-slate-500" style={{ background: getPieceColor(p.name) }} />{p.name}</div>)}</div></section>;
const ProductionSummary = ({ input, result, unused }: { input: OptimizerInput; result: StrategyResult; unused: number }) => <section className="rounded-lg border border-[#b9ead0] bg-gradient-to-br from-[#effdf6] to-[#e4faf1] p-3"><h2 className="text-lg font-bold">Production Summary (Best Strategy)</h2><div className="mt-1 font-bold text-[#07883e]">{result.garmentsPlaced} of {input.quantity} {input.garment}s can be produced</div><div className="mt-2 grid grid-cols-2 gap-y-2 text-sm"><Metric label="Fabric Used" value={`${result.fabricUsed.toFixed(1)} m`} /><Metric label="Unused Fabric" value={`${unused.toFixed(1)} m`} /><Metric label="Material Utilization" value={`${result.utilization.toFixed(1)}%`} green /><Metric label="Waste" value={`${result.wastePercent.toFixed(1)}% (${result.wasteArea.toFixed(2)} m²)`} red /><Metric label="Estimated Cost" value={`₹${Math.round(result.cost).toLocaleString('en-IN')}`} /></div><div className={`mt-2 rounded-md px-3 py-2 text-sm ${result.fits ? 'bg-[#d3f8e4] text-[#07883e]' : 'bg-amber-100 text-amber-800'}`}>{result.fits ? '✓ All requested garments fit in the given fabric roll!' : `Only ${result.garmentsPlaced} of ${input.quantity} requested garments fit; the remaining ${input.quantity - result.garmentsPlaced} need additional fabric.`}</div></section>;
const Metric = ({ label, value, green, red }: { label: string; value: string; green?: boolean; red?: boolean }) => <div><div className="text-[#4d6489]">{label}</div><div className={`mt-0.5 font-bold ${green ? 'text-[#07883e]' : red ? 'text-red-600' : ''}`}>{value}</div></div>;
const StrategyCard = ({ input, result, index, isBest, onZoom }: { input: OptimizerInput; result: StrategyResult; index: number; isBest: boolean; expanded: boolean; onZoom: () => void }) => { const config = [{ title: 'Strategy A', subtitle: 'Standard Straight Layout', header: 'bg-[#ffe8eb]', badge: 'Highest Waste', tone: 'text-red-600' }, { title: 'Strategy B', subtitle: 'Rotated Layout', header: 'bg-[#e8efff]', badge: 'Better', tone: 'text-blue-700' }, { title: 'Strategy C', subtitle: 'AI Optimized Nesting Layout', header: 'bg-[#e2faed]', badge: 'Optimized', tone: 'text-[#087d3c]' }][index]; return <article className={`overflow-hidden rounded-lg border bg-white ${isBest ? 'border-[#11a952] ring-1 ring-[#11a952]' : 'border-[#dbe4ef]'}`}><header className={`flex items-center justify-between p-4 ${config.header}`}><div><h2 className={`text-xl font-bold ${config.tone}`}>{config.title}</h2><p>{config.subtitle}</p></div><span className={`rounded-full px-4 py-2 text-sm font-bold ${isBest ? 'bg-[#11a952] text-white' : index === 1 ? 'bg-[#cbd9ff] text-blue-700' : 'bg-[#ffd3d8] text-red-600'}`}>{isBest && <Star className="mr-1 inline h-4 w-4 fill-current" />}{isBest ? 'BEST' : config.badge}</span></header><div className="grid grid-cols-[minmax(0,1.85fr)_minmax(125px,1fr)] gap-3 p-4"><div><LayoutOverview input={input} result={result} /><PieceKey input={input} /></div><div className="space-y-3 border-l border-[#e2e8f0] pl-3"><b className="text-sm">Metrics</b><Metric label="Total Garments Placed" value={`${result.garmentsPlaced} / ${input.quantity}`} /><Metric label="Fabric Used" value={`${result.fabricUsed.toFixed(1)} m (${(result.fabricUsed * input.width / 100).toFixed(2)} m²)`} /><Metric label="Pattern Area" value={`${result.patternArea.toFixed(2)} m²`} /><Metric label="Waste Area" value={`${result.wasteArea.toFixed(2)} m²`} /><Metric label="Waste Percentage" value={`${result.wastePercent.toFixed(1)}%`} red /><Metric label="Material Utilization" value={`${result.utilization.toFixed(1)}%`} green /><Metric label="Estimated Cost" value={`₹${Math.round(result.cost).toLocaleString('en-IN')}`} /></div></div><div className="px-4 pb-4"><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className={isBest ? 'h-full bg-[#13ad55]' : index === 1 ? 'h-full bg-[#4c71ee]' : 'h-full bg-[#f0768c]'} style={{ width: `${result.utilization}%` }} /></div><button onClick={onZoom} className="mt-3 w-full rounded-lg border border-[#d7e0eb] py-2 text-xs font-bold text-[#315781]">Zoom Cutting Layout</button></div></article> };
const PieceKey = ({ input }: { input: OptimizerInput }) => <div className="mt-2 border-t border-[#e1e8f0] pt-2 text-[10px] text-[#405b83]"><b className="block text-xs text-[#102548]">Pattern Piece Legend</b><div className="mt-1 grid grid-cols-2 gap-x-2 gap-y-1">{input.pieces.map((piece) => <span key={piece.id} className="flex items-center gap-1"><i className="h-3 w-3 rounded-sm border border-slate-400" style={{ background: getPieceColor(piece.name) }} /><b>{getPieceCode(piece.name)}</b> = {piece.name}</span>)}</div></div>;
const LayoutOverview = ({ input, result }: { input: OptimizerInput; result: StrategyResult }) => {
  const numbers = result.garmentsPlaced <= 5 ? Array.from({ length: result.garmentsPlaced }, (_, i) => i + 1) : [1, 2, 3, 4, 5, result.garmentsPlaced];
  return <div className="rounded-xl border border-[#587196] bg-[#f9fbfd] p-3"><div className="mb-3 text-center text-xs font-bold text-[#102548]">←──────── {input.width} cm (Fabric Width) ────────→</div><div className="space-y-3">{numbers.map((number, index) => <React.Fragment key={number}>{index === 5 && <div className="py-1 text-center text-sm font-black tracking-[.45em] text-[#657995]">···</div>}<GarmentPreviewBlock input={input} number={number} pieces={result.placements.filter((piece) => piece.garmentNumber === number)} /></React.Fragment>)}</div><div className="mt-3 rounded-md border border-dashed border-slate-400 bg-slate-100 px-3 py-2 text-center text-[10px] font-bold text-[#475569]">UNUSED FABRIC (WASTE) · {result.wastePercent.toFixed(1)}%</div><div className="mt-2 flex justify-between text-[10px] font-bold text-[#334d70]"><span>{result.garmentsPlaced} {input.garment}s placed</span><span>↕ {result.fabricUsed.toFixed(1)} m used</span></div></div>;
};
const GarmentPreviewBlock = ({ input, number, pieces }: { input: OptimizerInput; number: number; pieces: Placement[] }) => {
  if (!pieces.length) return null;
  const minX = Math.min(...pieces.map((piece) => piece.x)), minY = Math.min(...pieces.map((piece) => piece.y)), maxX = Math.max(...pieces.map((piece) => piece.x + piece.width)), maxY = Math.max(...pieces.map((piece) => piece.y + piece.height));
  const width = Math.max(1, maxX - minX), height = Math.max(1, maxY - minY);
  return <section className="overflow-hidden rounded-lg border border-[#42658d] bg-white"><div className="border-b border-[#cad8e8] bg-[#eef4fb] px-2 py-1 text-center text-[10px] font-extrabold tracking-wide text-[#071d3b]">{input.garment.toUpperCase()} #{number}</div><svg viewBox={`-2 -2 ${width + 4} ${height + 4}`} preserveAspectRatio="xMidYMid meet" className="block h-28 w-full bg-[#fffdf3]" aria-label={`${input.garment} ${number} pattern group`}>{pieces.map((piece) => <g key={piece.id}><title>{`${piece.name}: ${piece.rotated ? '90° rotation' : 'default orientation'}`}</title><rect x={piece.x - minX} y={piece.y - minY} width={piece.width} height={piece.height} rx="1.5" fill={piece.color} stroke="#172d4b" strokeWidth=".8" />{Math.min(piece.width, piece.height) >= 10 && <text x={piece.x - minX + piece.width / 2} y={piece.y - minY + piece.height / 2} textAnchor="middle" dominantBaseline="middle" fontSize={Math.min(12, Math.max(6, Math.min(piece.width, piece.height) / 2.2))} fontWeight="800" fill="#071d3b">{getPieceCode(piece.name)}</text>}</g>)}</svg></section>;
};
const CuttingDiagram = ({ input, result, expanded, scale: requestedScale, onZoom }: { input: OptimizerInput; result: StrategyResult; expanded: boolean; scale?: number; onZoom: () => void }) => {
  const usedCm = Math.max(1, result.fabricUsed * 100); const viewHeight = Math.max(usedCm, input.length * 100); const scale = requestedScale || (expanded ? 4.5 : 1);
  const groups = Array.from({ length: result.garmentsPlaced }, (_, index) => index + 1).map((number) => { const pieces = result.placements.filter((p) => p.garmentNumber === number); return { number, x: Math.min(...pieces.map((p) => p.x)), y: Math.min(...pieces.map((p) => p.y)), width: Math.max(...pieces.map((p) => p.x + p.width)) - Math.min(...pieces.map((p) => p.x)), height: Math.max(...pieces.map((p) => p.y + p.height)) - Math.min(...pieces.map((p) => p.y)) }; }).filter((group) => group.number <= 5 || group.number === result.garmentsPlaced);
  return <button onClick={onZoom} className="relative block rounded border border-slate-500 bg-white text-left" title="Close detailed layout"><svg viewBox={`-12 -12 ${input.width + 24} ${viewHeight + 24}`} className="block" style={{ width: `${(input.width + 24) * scale}px`, height: `${(viewHeight + 24) * scale}px` }}><defs><pattern id={`waste-${result.key}`} width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="5" stroke="#bdc5ce" strokeWidth="1" /></pattern><marker id={`arrow-${result.key}`} markerWidth="4" markerHeight="4" refX="2" refY="2" orient="auto"><path d="M0,0 L4,2 L0,4z" fill="#102548" /></marker></defs><line x1="0" y1="-6" x2={input.width} y2="-6" stroke="#102548" strokeWidth=".7" markerStart={`url(#arrow-${result.key})`} markerEnd={`url(#arrow-${result.key})`} /><text x={input.width / 2} y="-8" textAnchor="middle" fontSize="5" fill="#102548">{input.width} cm (Fabric Width)</text><rect width={input.width} height={viewHeight} fill={`url(#waste-${result.key})`} /><rect x="0" y="0" width={input.width} height={usedCm} fill="#fbf3c3" stroke="#152b4f" strokeWidth="1" />{groups.map((group) => <g key={group.number}><rect x={group.x - 1} y={group.y - 8} width={group.width + 2} height={group.height + 9} fill="none" stroke="#24446f" strokeWidth=".7" strokeDasharray="2 1" /><text x={group.x + group.width / 2} y={group.y - 2} textAnchor="middle" fontSize="6" fontWeight="800" fill="#071d3b">{input.garment} #{group.number}</text></g>)}{result.placements.map((p) => <PieceShape key={p.id} p={p} />)}<line x1="-6" y1="0" x2="-6" y2={usedCm} stroke="#102548" strokeWidth=".7" markerStart={`url(#arrow-${result.key})`} markerEnd={`url(#arrow-${result.key})`} /><text x="-8" y={usedCm / 2} textAnchor="middle" fontSize="5" fill="#102548" transform={`rotate(-90 -8 ${usedCm / 2})`}>{result.fabricUsed.toFixed(1)} m used</text><text x={input.width / 2} y={viewHeight - 4} textAnchor="middle" fontSize="5" fontWeight="700" fill="#102548">UNUSED FABRIC (WASTE)</text></svg></button>;
};
const pieceLabel = (p: Placement) => `${getPieceCode(p.name)} ${p.garmentNumber}`;
const PieceShape = ({ p }: { p: Placement }) => {
  const shortSide = Math.min(p.width, p.height);
  const showLabel = shortSide >= 18;
  const fontSize = Math.min(11, Math.max(8, shortSide / 2.4));
  const clipId = `label-clip-${p.id}`;
  return <g><title>{`${p.name} #${p.garmentNumber}\n${p.width} × ${p.height} cm\nRotation: ${p.rotated ? '90°' : '0°'}\nArea: ${(p.width * p.height / 10000).toFixed(3)} m²`}</title><defs><clipPath id={clipId}><rect x={p.x + 2} y={p.y + 2} width={Math.max(0, p.width - 4)} height={Math.max(0, p.height - 4)} rx="1" /></clipPath></defs><rect x={p.x} y={p.y} width={p.width} height={p.height} rx="2" fill={p.color} stroke="#172d4b" strokeWidth=".8" />{showLabel && <text x={p.x + p.width / 2} y={p.y + p.height / 2} textAnchor="middle" dominantBaseline="middle" fontSize={fontSize} fontWeight="800" letterSpacing=".2" fill="#071d3b" stroke="#ffffff" strokeWidth="1.6" paintOrder="stroke" clipPath={`url(#${clipId})`}>{pieceLabel(p)}</text>}</g>;
};
export default OptimizationResults;
